version: "3"

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=gestor_tiempos_bbdd
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3306

  spring-boot-jpa-docker-webapp:

    image: daw:latest
    ports:
      - 8080:8443
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestor_tiempos_bbdd?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: